apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    run: myapp
  namespace: labgke     # <<<---- YOUR NAMESPACE
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: myapp